<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>YC.EnemyRandomizerMod.BepInEx</RootNamespace>
		<DebugType>embedded</DebugType>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<MainVersion>1.0</MainVersion>
		<BuildVersion>$([System.DateTime]::UtcNow.ToString(yy))$([System.DateTime]::UtcNow.DayOfYear.ToString(000))</BuildVersion>
		<VersionTime>$([System.DateTime]::UtcNow.ToString(HHmm))</VersionTime>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>YC.EnemyRandomizerMod.BepInEx</AssemblyName>
		<Description>YC.Enemy Randomizer Mod</Description>
		<Product>$(Description)</Product>
		<Authors>BoL4oNoK</Authors>
		<Copyright>Copyright © BoL4oNoK $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
		<AssemblyVersion>$(MainVersion).$(BuildVersion).$(VersionTime)</AssemblyVersion>
		<Version>$(MainVersion).$(BuildVersion)</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<Deterministic>false</Deterministic>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<PackageReference>
			<PrivateAssets>none</PrivateAssets>
		</PackageReference>
	</ItemDefinitionGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseMod.Core\BaseMod.Core.csproj" />
		<ProjectReference Include="..\YC.EnemyRandomizerMod\YC.EnemyRandomizerMod.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\Libs\Tomlet.dll"
			Pack="false"
			CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<CopySource Include="$(TargetDir)*.dll" />
			<!--<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />-->
		</ItemGroup>

		<MakeDir Directories="$(SolutionDir)@Mods\BepInEx\$(AssemblyName)" />
		<Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Mods\BepInEx\$(AssemblyName)" />
		<!--<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Mods\$(AssemblyName)\%(RecursiveDir)" />-->
	</Target>

	<Target Name="PostPublish" AfterTargets="Publish" Condition="'$(Configuration)'=='Release'">
		<ItemGroup>
			<CopySource Include="$(PublishDir)*.dll" />
			<!--<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />-->
		</ItemGroup>

		<MakeDir Directories="$(SolutionDir)@Release\BepInEx\$(AssemblyName)\$(AssemblyName)" />
		<Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Release\BepInEx\$(AssemblyName)\$(AssemblyName)" />
		<!--<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)\$(AssemblyName)\%(RecursiveDir)" />-->
		<!--<Copy SourceFiles="$(ProjectDir)Gameplay Mod_Readme.rtf" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)" />-->
		<ZipDirectory SourceDirectory="$(SolutionDir)@Release\BepInEx\$(AssemblyName)" DestinationFile="$(SolutionDir)@Release\BepInEx\BepInEx-$(AssemblyName)-$(AssemblyVersion).zip" Overwrite="true" />
	</Target>
</Project>