<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPluginLib>true</IsPluginLib>

		<ModName>Yaradiels Crown. Unloader</ModName>
		<ModDescription>MelonLoader unloader mode for Yaradiels Crown</ModDescription>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseMod.Core\BaseMod.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\Libs\Assembly-CSharp.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>