<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>YC.GameplayMod</RootNamespace>
		<AssemblyName>YC.GameplayMod</AssemblyName>
		<Description>YC Gameplay Mod</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LavaGang.MelonLoader" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseMod.Core\BaseMod.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\Libs\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\Libs\Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Il2Cppcom.gator-dragon-games.jigglephysics">
		  <HintPath>..\Libs\Il2Cppcom.gator-dragon-games.jigglephysics.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>..\Libs\Il2CppInterop.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>		
		<Reference Include="Il2CppMagicaClothV2">
		  <HintPath>..\Libs\Il2CppMagicaClothV2.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>..\Libs\Il2Cppmscorlib.dll</HintPath>
		</Reference>
        <Reference Include="Tomlet">
            <HintPath>..\Libs\Tomlet.dll</HintPath>
        </Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>..\Libs\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>..\Libs\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<PropertyGroup>
			<OutBaseDir>..\@Mods\</OutBaseDir>
			<OutModsDir>$(OutBaseDir)Mods\</OutModsDir>
			<OutUserLibsDir>$(OutBaseDir)UserLibs\</OutUserLibsDir>
			<OutUserDataDir>$(OutBaseDir)UserData\$(AssemblyName)\</OutUserDataDir>
		</PropertyGroup>

		<ItemGroup>
			<ModDll Include="$(TargetDir)$(TargetFileName)" />
			<UserLibs Include="$(TargetDir)*.dll" Exclude="$(TargetDir)$(TargetFileName)" />
			<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />
		</ItemGroup>

		<MakeDir Directories="$(OutModsDir)" />
		<MakeDir Directories="$(OutUserLibsDir)" />

		<RemoveDir Directories="$(OutUserDataDir)" />
		<MakeDir Directories="$(OutUserDataDir)" />

		<Copy SourceFiles="@(ModDll)" DestinationFolder="$(OutModsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(UserLibs)" DestinationFolder="$(OutUserLibsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(OutUserDataDir)%(RecursiveDir)" />
	</Target>

	<Target Name="PostPublish" AfterTargets="Publish" Condition="'$(Configuration)'=='Release'">
		<PropertyGroup>
			<OutReleaseDir>..\@Release\</OutReleaseDir>
			<OutBaseDir>$(OutReleaseDir)$(AssemblyName)\</OutBaseDir>
			<OutModsDir>$(OutBaseDir)Mods\</OutModsDir>
			<OutUserLibsDir>$(OutBaseDir)UserLibs\</OutUserLibsDir>
			<OutUserDataDir>$(OutBaseDir)UserData\$(AssemblyName)\</OutUserDataDir>
		</PropertyGroup>

		<ItemGroup>
			<ModDll Include="$(TargetDir)$(TargetFileName)" />
			<UserLibs Include="$(TargetDir)*.dll" Exclude="$(TargetDir)$(TargetFileName)" />
			<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />
			<ReadmeFiles Include="$(ProjectDir)$(TargetName)_Readme.*" />
		</ItemGroup>

		<RemoveDir Directories="$(OutBaseDir)" />
		<MakeDir Directories="$(OutModsDir)" />
		<MakeDir Directories="$(OutUserLibsDir)" />
		<MakeDir Directories="$(OutUserDataDir)" />

		<Copy SourceFiles="@(ModDll)" DestinationFolder="$(OutModsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(UserLibs)" DestinationFolder="$(OutUserLibsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(OutUserDataDir)%(RecursiveDir)" />
		<Copy SourceFiles="@(ReadmeFiles)" DestinationFolder="$(OutBaseDir)" />

		<ZipDirectory SourceDirectory="$(OutBaseDir)" DestinationFile="$(OutReleaseDir)$(AssemblyName)-$(AssemblyVersion).zip" Overwrite="true" />
	</Target>
</Project>