<Project>
    <PropertyGroup>		
        <TargetFramework>net6.0</TargetFramework>
        <Platforms>x64</Platforms>
        <DebugType>embedded</DebugType>

        <AnalysisLevel>latest</AnalysisLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup>
        <IsPluginLib Condition="'$(IsPluginLib)' == ''">false</IsPluginLib>
        
        <MainVersion>1.0</MainVersion>
        <BuildVersion>$([System.DateTime]::UtcNow.ToString(yy))$([System.DateTime]::UtcNow.DayOfYear.ToString(000))</BuildVersion>
        <VersionTime>$([System.DateTime]::UtcNow.ToString(HHmm))</VersionTime>
        <AssemblyVersion>$(MainVersion).$(BuildVersion).$(VersionTime)</AssemblyVersion>
        <Version>$(MainVersion).$(BuildVersion)</Version>
        <Deterministic>false</Deterministic>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
        
        <Authors>BoL4oNoK</Authors>
        <Copyright>Copyright © $(Authors) $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
        <GitRepoUrl>https://github.com/MaxAn26/YC-Gameplay-Mod</GitRepoUrl>
    </PropertyGroup>
    
    <ItemDefinitionGroup>
        <PackageReference>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <Reference>
            <Private>false</Private>
        </Reference>
    </ItemDefinitionGroup>
</Project>
