<Project>
<Target Name="GenerateModInfo" BeforeTargets="BeforeCompile">
	<!-- Путь к файлу -->
	<PropertyGroup>
		<GeneratedFile>$(IntermediateOutputPath)ModInfo.cs</GeneratedFile>
	</PropertyGroup>

	<!-- Запись содержимого -->
	<WriteLinesToFile File="$(GeneratedFile)"
					  Overwrite="true"
					  Lines="using System%3B
						internal static class ModInfo {
							public const string GUID = &quot;$(AssemblyName)&quot;%3B
							public const string NAME = &quot;$(Title)&quot;%3B
							public const string VERSION = &quot;$(Version)&quot;%3B
							public const string AUTHORS = &quot;$(Authors)&quot;%3B
                            public const string URL = &quot;$(GitRepoUrl)&quot;%3B
						}"
					  />

	<!-- Подключаем файл к компиляции -->
	<ItemGroup>
		<Compile Include="$(GeneratedFile)" />
	</ItemGroup>
</Target>
</Project>
