<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\build\PluginInfo.targets" />
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
		  https://api.nuget.org/v3/index.json;
		  https://nuget.bepinex.dev/v3/index.json;
		  https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>YC.EnemyRandomizerMod</RootNamespace>
		<DebugType>embedded</DebugType>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<MainVersion>1.0</MainVersion>
		<BuildVersion>$([System.DateTime]::UtcNow.ToString(yy))$([System.DateTime]::UtcNow.DayOfYear.ToString(000))</BuildVersion>
		<VersionTime>$([System.DateTime]::UtcNow.ToString(HHmm))</VersionTime>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>YC.EnemyRandomizerMod</AssemblyName>
		<Description>YC.Enemy Randomizer Mod</Description>
		<Product>$(Description)</Product>
		<Authors>BoL4oNoK</Authors>
		<Copyright>Copyright © BoL4oNoK $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
		<AssemblyVersion>$(MainVersion).$(BuildVersion).$(VersionTime)</AssemblyVersion>
		<Version>$(MainVersion).$(BuildVersion)</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<Deterministic>false</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LavaGang.MelonLoader" Version="0.7.1" />
		<PackageReference Include="Samboy063.Tomlet" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseMod.Core\BaseMod.Core.csproj" />
	</ItemGroup>

	<ItemGroup>		
		<Reference Include="0Harmony">
			<HintPath>..\Libs\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\Libs\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>..\Libs\Il2Cppmscorlib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>..\Libs\Il2CppInterop.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<CopySource Include="$(TargetDir)*.dll" />
			<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />
		</ItemGroup>

		<MakeDir Directories="$(SolutionDir)@Mods\Mods" />
		<MakeDir Directories="$(SolutionDir)@Mods\UserData\$(AssemblyName)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)@Mods\Mods" />
		<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Mods\UserData\$(AssemblyName)\%(RecursiveDir)" />

		<!-- <MakeDir Directories="$(SolutionDir)@Mods\$(AssemblyName)" /> -->
		<!-- <Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Mods\$(AssemblyName)" /> -->
		<!-- <Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Mods\$(AssemblyName)\%(RecursiveDir)" /> -->
	</Target>

	<Target Name="PostPublish" AfterTargets="Publish" Condition="'$(Configuration)'=='Release'">
		<ItemGroup>
			<CopySource Include="$(PublishDir)*.dll" />
			<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />
		</ItemGroup>

		<MakeDir Directories="$(SolutionDir)@Release\$(AssemblyName)\Mods" />
		<MakeDir Directories="$(SolutionDir)@Release\$(AssemblyName)\UserData\$(AssemblyName)" />
		<Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)\Mods" />
		<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)\UserData\$(AssemblyName)\%(RecursiveDir)" />
		<!--<Copy SourceFiles="$(ProjectDir)Gameplay Mod_Readme.rtf" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)" />-->
		<ZipDirectory SourceDirectory="$(SolutionDir)@Release\$(AssemblyName)" DestinationFile="$(SolutionDir)@Release\$(AssemblyName)-$(AssemblyVersion).zip" Overwrite="true" />
	</Target>
</Project>