<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\build\PluginInfo.targets" />
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>YC.GameTrainerMod</RootNamespace>
		<DebugType>embedded</DebugType>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<MainVersion>1.0</MainVersion>
		<BuildVersion>$([System.DateTime]::UtcNow.ToString(yy))$([System.DateTime]::UtcNow.DayOfYear.ToString(000))</BuildVersion>
		<VersionTime>$([System.DateTime]::UtcNow.ToString(HHmm))</VersionTime>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>YC.GameTrainerMod</AssemblyName>
		<Description>YC.Game Trainer Mod</Description>
		<Product>$(Description)</Product>
		<Authors>BoL4oNoK</Authors>
		<Copyright>Copyright © BoL4oNoK $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
		<AssemblyVersion>$(MainVersion).$(BuildVersion).$(VersionTime)</AssemblyVersion>
		<Version>$(MainVersion).$(BuildVersion)</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<Deterministic>false</Deterministic>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<PackageReference>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<Reference>
			<Private>false</Private>
		</Reference>
	</ItemDefinitionGroup>

	<ItemGroup>
		<PackageReference Include="LavaGang.MelonLoader" Version="0.7.2" />
		<PackageReference Include="Samboy063.Tomlet" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseMod.Core\BaseMod.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\Libs\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\Libs\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>..\Libs\Il2Cppmscorlib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>..\Libs\Il2CppInterop.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>..\Libs\UnityEngine.IMGUIModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>..\Libs\UnityEngine.InputLegacyModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<PropertyGroup>
			<OutBaseDir>..\@Mods\</OutBaseDir>
			<OutModsDir>$(OutBaseDir)Mods\</OutModsDir>
			<OutUserLibsDir>$(OutBaseDir)UserLibs\</OutUserLibsDir>
			<OutUserDataDir>$(OutBaseDir)UserData\$(AssemblyName)\</OutUserDataDir>
		</PropertyGroup>

		<ItemGroup>
			<ModDll Include="$(TargetDir)$(TargetFileName)" />
			<UserLibs Include="$(TargetDir)*.dll" Exclude="$(TargetDir)$(TargetFileName)" />
		</ItemGroup>

		<MakeDir Directories="$(OutModsDir)" />
		<MakeDir Directories="$(OutUserLibsDir)" />

		<RemoveDir Directories="$(OutUserDataDir)" />
		<MakeDir Directories="$(OutUserDataDir)" />

		<Copy SourceFiles="@(ModDll)" DestinationFolder="$(OutModsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(UserLibs)" DestinationFolder="$(OutUserLibsDir)" SkipUnchangedFiles="true" />
	</Target>

	<Target Name="PostPublish" AfterTargets="Publish" Condition="'$(Configuration)'=='Release'">
		<PropertyGroup>
			<OutReleaseDir>..\@Release\</OutReleaseDir>
			<OutBaseDir>$(OutReleaseDir)$(AssemblyName)\</OutBaseDir>
			<OutModsDir>$(OutBaseDir)Mods\</OutModsDir>
			<OutUserLibsDir>$(OutBaseDir)UserLibs\</OutUserLibsDir>
			<OutUserDataDir>$(OutBaseDir)UserData\$(AssemblyName)\</OutUserDataDir>
		</PropertyGroup>

		<ItemGroup>
			<ModDll Include="$(TargetDir)$(TargetFileName)" />
			<UserLibs Include="$(TargetDir)*.dll" Exclude="$(TargetDir)$(TargetFileName)" />
			<ReadmeFiles Include="$(ProjectDir)$(TargetName)_Readme.*" />
		</ItemGroup>

		<RemoveDir Directories="$(OutBaseDir)" />
		<MakeDir Directories="$(OutModsDir)" />
		<MakeDir Directories="$(OutUserLibsDir)" />
		<MakeDir Directories="$(OutUserDataDir)" />

		<Copy SourceFiles="@(ModDll)" DestinationFolder="$(OutModsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(UserLibs)" DestinationFolder="$(OutUserLibsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(ReadmeFiles)" DestinationFolder="$(OutBaseDir)" />

		<ZipDirectory SourceDirectory="$(OutBaseDir)" DestinationFile="$(SolutionDir)@Release\$(AssemblyName)-$(AssemblyVersion).zip" Overwrite="true" />
	</Target>
</Project>