<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RootNamespace>YC.EnemyRandomizerMod.Melon</RootNamespace>
		<DebugType>embedded</DebugType>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<MainVersion>1.0</MainVersion>
		<BuildVersion>$([System.DateTime]::UtcNow.ToString(yy))$([System.DateTime]::UtcNow.DayOfYear.ToString(000))</BuildVersion>
		<VersionTime>$([System.DateTime]::UtcNow.ToString(HHmm))</VersionTime>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>YC.EnemyRandomizerMod.Melon</AssemblyName>
		<Description>YC.Enemy Randomizer Mod</Description>
		<Product>$(Description)</Product>
		<Authors>BoL4oNoK</Authors>
		<Copyright>Copyright © BoL4oNoK $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
		<AssemblyVersion>$(MainVersion).$(BuildVersion).$(VersionTime)</AssemblyVersion>
		<Version>$(MainVersion).$(BuildVersion)</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<Deterministic>false</Deterministic>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<PackageReference>
			<PrivateAssets>none</PrivateAssets>
		</PackageReference>
	</ItemDefinitionGroup>

	<ItemGroup>
	  <PackageReference Include="LavaGang.MelonLoader" Version="0.7.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseMod.Core\BaseMod.Core.csproj" />
		<ProjectReference Include="..\YC.EnemyRandomizerMod\YC.EnemyRandomizerMod.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="0Harmony">
	    <HintPath>..\Libs\0Harmony.dll</HintPath>
		  <Private>false</Private>
	  </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<CopySource Include="$(TargetDir)*.dll" />
			<!--<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />-->
		</ItemGroup>

		<MakeDir Directories="$(SolutionDir)@Mods\Melon\$(AssemblyName)" />
		<Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Mods\Melon\$(AssemblyName)" />
		<!--<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Mods\$(AssemblyName)\%(RecursiveDir)" />-->
	</Target>

	<Target Name="PostPublish" AfterTargets="Publish" Condition="'$(Configuration)'=='Release'">
		<ItemGroup>
			<CopySource Include="$(PublishDir)*.dll" />
			<!--<PreConfiguredFiles Include="$(ProjectDir)PreConfiguredFiles\**\*.*" />-->
		</ItemGroup>

		<MakeDir Directories="$(SolutionDir)@Release\Melon\$(AssemblyName)\$(AssemblyName)" />
		<Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Release\Melon\$(AssemblyName)\$(AssemblyName)" />
		<!--<Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)\$(AssemblyName)\%(RecursiveDir)" />-->
		<!--<Copy SourceFiles="$(ProjectDir)Gameplay Mod_Readme.rtf" DestinationFolder="$(SolutionDir)@Release\$(AssemblyName)" />-->
		<ZipDirectory SourceDirectory="$(SolutionDir)@Release\Melon\$(AssemblyName)" DestinationFile="$(SolutionDir)@Release\Melon\Melon-$(AssemblyName)-$(AssemblyVersion).zip" Overwrite="true" />
	</Target>
</Project>
