<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<DebugType>embedded</DebugType>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<MainVersion>1.0</MainVersion>
		<BuildVersion>$([System.DateTime]::UtcNow.ToString(yy))$([System.DateTime]::UtcNow.DayOfYear.ToString(000))</BuildVersion>
		<VersionTime>$([System.DateTime]::UtcNow.ToString(HHmm))</VersionTime>
	</PropertyGroup>
	<PropertyGroup>
		<Product>$(AssemblyName)</Product>
		<Authors>BoL4oNoK</Authors>
		<Copyright>Copyright © BoL4oNoK $([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
		<AssemblyVersion>$(MainVersion).$(BuildVersion).$(VersionTime)</AssemblyVersion>
		<Version>$(MainVersion).$(BuildVersion)</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<PackageReference>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<Reference>
			<Private>false</Private>
		</Reference>
	</ItemDefinitionGroup>
	<ItemGroup>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>..\Libs\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>..\Libs\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<MakeDir Directories="$(SolutionDir)@Mods\UserLibs" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)@Mods\UserLibs" />

		<!-- <MakeDir Directories="$(SolutionDir)@Mods\$(AssemblyName)" /> -->
		<!-- <Copy SourceFiles="@(CopySource)" DestinationFolder="$(SolutionDir)@Mods\$(AssemblyName)" /> -->
		<!-- <Copy SourceFiles="@(PreConfiguredFiles)" DestinationFolder="$(SolutionDir)@Mods\$(AssemblyName)\%(RecursiveDir)" /> -->
	</Target>
</Project>
